

.PHONY: raster_logo

raster_logo:
	rsvg-convert -w 16 -h 16 nl_logo.svg -o generated/nl_logo_16.png
	rsvg-convert -w 32 -h 32 nl_logo.svg -o generated/nl_logo_32.png
	rsvg-convert -w 64 -h 64 nl_logo.svg -o generated/nl_logo_64.png
	rsvg-convert -w 128 -h 128 nl_logo.svg -o generated/nl_logo_128.png
	rsvg-convert -w 256 -h 256 nl_logo.svg -o generated/nl_logo_256.png
	rsvg-convert -w 512 -h 512 nl_logo.svg -o generated/nl_logo_512.png

	rsvg-convert -w 16 -h 16 nl_logo_letters.svg -o generated/nl_logo_letters_16.png
	rsvg-convert -w 32 -h 32 nl_logo_letters.svg -o generated/nl_logo_letters_32.png
	rsvg-convert -w 64 -h 64 nl_logo_letters.svg -o generated/nl_logo_letters_64.png
	rsvg-convert -w 128 -h 128 nl_logo_letters.svg -o generated/nl_logo_letters_128.png
	rsvg-convert -w 256 -h 256 nl_logo_letters.svg -o generated/nl_logo_letters_256.png
	rsvg-convert -w 512 -h 512 nl_logo_letters.svg -o generated/nl_logo_letters_512.png